### ISSUE TITLE
[BUG] 'NoneType' object has no attribute 'entrytype' error

### ISSUE THREAD

**Issue by shuchaa** [saketkc/pysradb#158]
**Describe the bug**
Since updating from version 1.0.1 to 1.3.1 sometimes, while using the function gse-to-srp, for some GSEs, the following error occurs:
![image](https://user-images.githubusercontent.com/56719707/167496268-0d97cfc0-d528-40de-89ca-c0b41b8b6064.png)

while in version 1.0.1 it works fine for the same GSEs.

**To Reproduce**
`pysradb gse-to-srp GSE164522`

**Desktop (please complete the following information):**
 - OS: Both Windows & Linux.
 - Python version 3.10

**Additional context**

**Comment by saketkc** [comment]
This GSE doesn't have an SRP attached: https://www.ncbi.nlm.nih.gov/bioproject/PRJNA691050

```bash
 $ pysradb gse-to-srp GSE164522
No results found for ['GSE164522']
 $ pysradb --version
pysradb 1.0.1
```

Though, I agree with 1.3.1, the error is not graceful. Does this make sense?

**Comment by saketkc** [comment]
Also, the page says "Raw data not provided for this record" at the bottom. Closing this.
